version: 2.1

jobs:
  build_quality_release:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "package.json" }}
      - run:
          name: install
          command: npm i --no-save
      - run:
          name: lint
          command: npm run lint
      - run:
          name: test
          command: npm run test
      - run:
          name: build
          command: npm run build
      - run:
          name: release
          command: npm run semantic-release || true
      - save_cache:
          key: dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules

workflows:
  build_quality_release:
    jobs:
      - build_quality_release
